#+TITLE: propositum | =scoop= bucket

This repository stores [[https://github.com/lukesampson/scoop][scoop]] manifest files in JSON format. The manifest files are used to install and configure the different components of the [[https://github.com/xeijin/propositum][propositum]]. In some cases these are simply modified versions of the relevant manifest files from the main scoop bucket.

You may find these manifests instructional in automating the installation of any of these components with scoop. I recommend forking this repo or copying the contents of a given manifest to your own, as these manifest files are often heavily customised to suit my own needs.

* Usage

If you wish to use the repo directly, [[https://scoop.sh][install scoop]] then in =powershell= or =cmd.exe= enter the following command to add the new bucket

#+BEGIN_SRC powershell
  scoop bucket add propositum 'https://github.com/xeijin/propositum-bucket.git'
#+END_SRC

Note that all of the components in this repo have the suffix =-p= appended (to avoid conflict with the main and extras scoop repos).

To install an app

#+BEGIN_SRC powershell
  scoop install knime-p
#+END_SRC
